--Afetividade
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ler um livro','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Estudar','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Brincar','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Meditar','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Escrever','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Voluntariado','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidado pessoal','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Jogar','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Usar celular/tablet','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Exercícios','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ouvir música','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Sair com os amigos','A','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar das plantas','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer dever de casa','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Limpar casa','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer compras','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Lavar roupas','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Arrumar casa','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Tirar lixo','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar do animal','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar do bebê','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Lavar carro','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer extra-classe','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Consertar casa','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Organizar orçamento doméstico','A','T');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer refeição','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Levar/buscar de festa','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir à escola','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer higiene pessoal','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ver TV','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Dormir','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Comer','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir ao trabalho','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir ao médico','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Viajar','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Conversar','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Passear','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ver filme','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Jogar','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir a um evento','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Construir algo','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar das plantas','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer dever de casa','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Limpar casa','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer compras','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Lavar roupas','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Arrumar casa','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Tirar lixo','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar do animal','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar do bebê','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Lavar carro','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer extra-classe','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Consertar casa','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Organizar orçamento doméstico','A','W');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer refeição','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Levar/buscar de festa','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir à escola','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer higiene pessoal','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ver TV','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Dormir','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Comer','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir ao trabalho','A','G');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Ir ao médico','A','G');
--Comportamento
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Arrumar a cama','T','A');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Preparar seu café da manhã','T','A');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Estudar ou fazer a tarefa','T','E');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Comer ao menos 4 tipos de alimentos','T','R');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer a oração antes das refeições ou antes de dormir','T','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer uma tarefa doméstica','T','D');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Não brigar, responder ou falar palavrão','T','C');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Não deixar suas coisas espalhadas pela casa','T','A');

INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Arrumar a cama','M','A');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Fazer a tarefa','M','E');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Lavar a louça','M','D');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Comer ao menos 4 tipos de alimentos','M','R');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cortar a grama','M','D');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Varrer a casa','M','D');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Cuidar do bicho de estimação','M','I');

INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Refeição','F','R');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Comportamento','F','C');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Higiene','F','H');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Obrigações','F','A');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Espiritualidade','F','I');
INSERT INTO tipo_atividade(des_tipo_atividade,tip_atividade, ind_proposito)VALUES('Atividade física','F','F');